# Section 1: Getting Started

## Expressions

Python handles several types of expressions; e.g., string, numerical and list expressions.

In [1]:
2 
# Numerical expression. 
# Note that statements following the pound symbol are not evaluated by Python.
# These are "comments" on your code. 
# Including lots of comments in your code is crucial for improving readability.

2

In [2]:
2.009 # Numerical expression

2.009

In [3]:
'abcd' # String expression. Note the quotation marks.

'abcd'

In [4]:
"abcd" # Double quotes also produces a string expression.

'abcd'

In [5]:
abcd # Without quotes, we get an error. Python wants to treat this as a variable (see the next section).

NameError: name 'abcd' is not defined

In [6]:
[2,3,4,5] # List expression. Elements of the list are numerical expressions.

[2, 3, 4, 5]

In [7]:
['a','b','c','defg'] # A list expression whose elements are string expressions.

['a', 'b', 'c', 'defg']

In [1]:
['a',234] # Lists can contain different types of expressions.

['a', 234]

In [4]:
[['a','b','c'],[123],'1',2] # Lists can contain lists.

[['a', 'b', 'c'], [123], '1', 2]

## Operations

There are several operations that can be performed on each type of expression. Let's explore some possiblilites.

### Numerical Operations

In [8]:
2+3 # Addition

5

In [9]:
2*3 # Multiplication

6

In [10]:
2**3 # Exponentiation

8

In [5]:
2**1000 # Note the "L" at the end of the output. This indicates that the type is a "long integer".

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376L

In [6]:
(2**3)**2+45-7*6 # Combinations of operations.

67

### Exercise
By playing around with examples, determine the numerical operation performed by the following symbols:
/ and %

### String Operations

In [16]:
'abcd'+'efgh' # Concatenation

'abcdefgh'

### List Operations

In [17]:
[1,2,3]+[4,5,6] # This is also concatenation, not vector addition!

[1, 2, 3, 4, 5, 6]

It makes sense that the above is concatenation, since it should make sense for lists of string expressions.

In [18]:
['a','b','c']+['cat','dog']

['a', 'b', 'c', 'cat', 'dog']

To perform vector operations, we need to use a package. A package is a collection of functions which need to be imported in order to use. A common package for linear algebra is called "numpy".

In [19]:
import numpy # Use this command to import numpy

To get vectors, we enter them as a new type of expression: numpy arrays. 

In [20]:
numpy.array([1,2,3])

array([1, 2, 3])

In [21]:
numpy.array([1,2,3])+numpy.array([4,5,6]) # numpy arrays can be added.

array([5, 7, 9])

In [22]:
numpy.array(['a','b','c'])+numpy.array(['cat','dog']) # This does not make sense!

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('S3') dtype('S3') dtype('S3')

We can also represent matrices as numpy arrays and perform standard operations.

In [23]:
numpy.array([[1,2,3],[4,5,6]]) # A 2x3 matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
numpy.array([[1,2,3],[4,5,6]])+numpy.array([[1,0,0],[0,0,0]]) # Matrices can be added

array([[2, 2, 3],
       [4, 5, 6]])

In [25]:
numpy.array([[1,2,3],[4,5,6]])*numpy.array([[2,1,0],[0,1,0]]) 
# This is not matrix multiplication. It multiplies matrices entry-wise.

array([[2, 2, 0],
       [0, 5, 0]])

We will see below how to multiply matrices in numpy. This is demonstrated in the "Functions" section.
In general, we will use the numpy package extensively in this course.

## Variables
In the operations above, we typed out the expression in each line. It is much more economical to store expressions in variables.

In [26]:
a = 2 # We define the variable "a" to represent the number 2.

In [27]:
b = 3

In [28]:
a*b # We can now perform operations on the variables

6

In [29]:
c = a**b # We can also define new variables by performing operations on the old ones
print(c)

8


Notice that there is no output when we define a variable. This is why the command print(c) was included in the previous cell.

In [30]:
string1 = 'cat'
string2 = 'dog'
string1+string2

'catdog'

Virtually any string of numbers and letters can be used as a variable. Some symbols are reserved, however. For example, we can't use "2" to denote a variable. 

In [31]:
for = 5 
# 'for' is reserved to denote a command in a 'for loop'. This will be discussed below. 
# We get an error message if we attempt to use 'for' as a variable name. 

SyntaxError: invalid syntax (<ipython-input-31-50d8479d7dac>, line 1)

We can use variables to store any type of expression, such as lists or numpy arrays.

In [32]:
L = ['a','b','c','d']

In [33]:
L + ['e','f']

['a', 'b', 'c', 'd', 'e', 'f']

In [34]:
aa = numpy.array([[3,2],[1,1]])
bb = numpy.array([[2,2],[3,3]])
aa+bb

array([[5, 4],
       [4, 4]])

Variables can be redefined.

In [35]:
a = 1
a = 2
print(a)

2


Variables can be redefined recursively.

In [36]:
a = a+1
print(a)

3


In [37]:
L = L + ['p','q','r','s']
print(L)

['a', 'b', 'c', 'd', 'p', 'q', 'r', 's']


# Section 2: Functions, Conditionals, Loops
## Functions
Python has many built-in functions. These are rules which take one (or several) expression(s) to (an)other expression(s), possibly of different types.

In [38]:
len('abc') # For example, "len()" is a function which takes a string to an integer.

3

In [39]:
string1 = 'abc123xyz' # Functions can be applied to variables.
len(string1)

9

In [40]:
list1 = ['cat','dog','mouse'] # len() can also take a list as input
len(list1)

3

The "type()" function tells you what type of expression the input is.

In [41]:
type('abc')

str

In [42]:
type(2) # Notice that 2 is a numerical expression, but is in particular an integer.

int

In [43]:
type(2.09) # The numerical expression 2.09 is "float" type.

float

In [44]:
type([1,2,3])

list

In [46]:
type(numpy.array([1,2,3]))

numpy.ndarray

"str()" is a function which converts a numerical expression to a string.

In [47]:
str(12345)

'12345'

Integers can be converted to floating point expressions via "float()".

In [7]:
float(2)

2.0

In [9]:
float('abc') # We can't convert strings to floats.

ValueError: could not convert string to float: abc

### Functions in the math package
Other basic numerical operations are not included in basic Python

In [48]:
sqrt(2)

NameError: name 'sqrt' is not defined

In [49]:
log(2)

NameError: name 'log' is not defined

To get access to these operations, we can import a package. In this case, we use the "math" package. 

In [50]:
import math

To use a function in the math package, we use the syntax "math.function()". This tells Python to use the function "function" from the package "math". For example:

In [51]:
math.sqrt(2)

1.4142135623730951

In [52]:
math.log(2)

0.6931471805599453

We will import packages frequently. Here are some tricks which are commonly used.

In [53]:
import math as ma # Use an abbreviation for the imported package

In [54]:
ma.sqrt(2)

1.4142135623730951

In [55]:
ma.log(2)

0.6931471805599453

Import specific functions from a package. We can abbreviate the function names if we want

In [56]:
from math import sqrt as sq

In [57]:
sq(2)

1.4142135623730951

### Functions in the numpy Package
Let's import numpy with an abbreviation. Common packages have "standard" abbreviations. That is, if you look at someone else's code, you will frequently see numpy imported as "np". 

In [58]:
import numpy as np

In [59]:
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[1,0,0],[0,1,1]])

To multiply numpy arrays, we use the function "matmul" from the numpy package. This function takes two matrices of the appropriate dimensions and computes their product. To call the function, we use the syntax np.matmul().

In [60]:
np.matmul(X,Y)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

The previous command gives an error message, because the matrices don't make sense to multiply. To get a matrix of the correct size, we could use the transpose function.

In [61]:
Z = np.transpose(Y)

In [62]:
np.matmul(X,Z)

array([[ 1,  5],
       [ 4, 11]])

Some other useful functions are "size" and "shape".

In [63]:
np.size(X)

6

In [64]:
np.shape(X)

(2, 3)

### Defining functions
The power of learning a programming language is the ability to define your own functions! The syntax that is used to define a function is illustrated below.
This tells us that we define a function named "square" with a single input "x". The function returns the input times itself. 

In [65]:
def square(x):
    return x*x
# The colon and "return" are crucial to define the function.

In [66]:
square(2)

4

In [67]:
a = 5
square(a)

25

Functions can be composed.

In [68]:
ma.sqrt(square(2))

2.0

In [69]:
square(ma.sqrt(2)) # The output shows some numerical error in the square root function.

2.0000000000000004

We can define functions which take/return any combination of expression(s).

In [70]:
def add_exclamation_point(string): # Descriptive function names are highly recommended.
    return string+'!'

In [71]:
add_exclamation_point('hello')

'hello!'

In [72]:
add_exclamation_point(123) # This will give an error

TypeError: unsupported operand type(s) for +: 'int' and 'str'

### Exercise
Define a function "digits()" which takes a positive integer and returns its number of digits. Use it to compute the number of digits in 2**1000.

In [73]:
def digits(x):
    return len(str(x))

In [74]:
digits(2**1000)

302

## Conditionals
We can write more interesting functions using conditionals. The output of the function can depend on whether or not a given condition holds. The syntax of a conditional is demonstrated by the following example.

In [75]:
def is_this_a_string(x):
    if type(x)==str:       # Notice the double equals and the colon
        return 'Yes'
    else:                  # Colon appears here too
        return 'No'

In [76]:
is_this_a_string(1)

'No'

In [77]:
is_this_a_string('abc')

'Yes'

Another example:

In [12]:
def collatz(n):
    if n % 2 == 0:
        return n/2
    else:
        return 3*n + 1

In [13]:
collatz(3)

10

In [80]:
collatz(_) # "_" is a variable which holds the last value computed.

5

In [10]:
_

2.0

Conditionals can involve multiple conditions by using "elif", which means "else, if".

In [26]:
def sign(x):  # Input is a float
    if x < 0:
        return 'The number '+str(x)+' is negative'
    elif x>0:
        return 'The number '+str(x)+' is positive'
    else:
        return 'The number '+str(x)+' is neither positive nor negative'  
    # In the last step we just use "else", since all other possibilities have been ruled out. 

In [27]:
print(sign(-1),sign(0),sign(1))

('The number -1 is negative', 'The number 0 is neither positive nor negative', 'The number 1 is positive')
